# Generated by Django 5.0.7 on 2025-04-02 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filio', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resume',
            name='file',
        ),
        migrations.RemoveField(
            model_name='resume',
            name='title',
        ),
        migrations.RemoveField(
            model_name='resume',
            name='uploaded_at',
        ),
        migrations.AddField(
            model_name='resume',
            name='name',
            field=models.CharField(default='My Resume', max_length=100),
        ),
        migrations.AddField(
            model_name='resume',
            name='pdf',
            field=models.FileField(default='default.pdf', upload_to='resumes/'),
        ),
    ]
