# Generated by Django 5.2.4 on 2025-11-13 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filio', '0002_remove_resume_file_remove_resume_title_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resume',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='resume',
            name='pdf',
            field=models.FileField(upload_to='Resumes/'),
        ),
    ]
